"""add_vector_recommendations

Revision ID: bc5a0d40884f
Revises: 
Create Date: 2026-07-21 10:40:05.378299

"""
"""add_vector_recommendations

Revision ID: bc5a0d40884f
Revises: 
Create Date: 2026-07-21 10:40:05.378299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'bc5a0d40884f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('is_foundational', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_nodes_tags'), 'resource_nodes', ['tags'], unique=False)
    op.create_table('user_skill_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weak_concepts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_interest_centroids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_centroid', sa.String(), nullable=True),
    sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_skill_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interest_centroids_user_id'), 'user_interest_centroids', ['user_id'], unique=False)
    op.drop_constraint(op.f('artifacts_tenant_id_fkey'), 'artifacts', type_='foreignkey')
    op.drop_constraint(op.f('artifacts_curriculum_id_fkey'), 'artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'artifacts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artifacts', 'curricula', ['curriculum_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('checkpoints_segment_id_fkey'), 'checkpoints', type_='foreignkey')
    op.drop_constraint(op.f('checkpoints_curriculum_id_fkey'), 'checkpoints', type_='foreignkey')
    op.drop_constraint(op.f('checkpoints_concept_id_fkey'), 'checkpoints', type_='foreignkey')
    op.create_foreign_key(None, 'checkpoints', 'curricula', ['curriculum_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'checkpoints', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'checkpoints', 'segments', ['segment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('concept_edges_source_id_fkey'), 'concept_edges', type_='foreignkey')
    op.drop_constraint(op.f('concept_edges_target_id_fkey'), 'concept_edges', type_='foreignkey')
    op.create_foreign_key(None, 'concept_edges', 'concepts', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'concept_edges', 'concepts', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('concepts_curriculum_id_fkey'), 'concepts', type_='foreignkey')
    op.create_foreign_key(None, 'concepts', 'curricula', ['curriculum_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_curricula_user'), table_name='curricula')
    op.drop_constraint(op.f('curricula_tenant_id_fkey'), 'curricula', type_='foreignkey')
    op.create_foreign_key(None, 'curricula', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('eval_results_exercise_id_fkey'), 'eval_results', type_='foreignkey')
    op.drop_constraint(op.f('eval_results_session_event_id_fkey'), 'eval_results', type_='foreignkey')
    op.create_foreign_key(None, 'eval_results', 'session_events', ['session_event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'eval_results', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('exercises_checkpoint_id_fkey'), 'exercises', type_='foreignkey')
    op.create_foreign_key(None, 'exercises', 'checkpoints', ['checkpoint_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('segments_curriculum_id_fkey'), 'segments', type_='foreignkey')
    op.create_foreign_key(None, 'segments', 'curricula', ['curriculum_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('session_events_session_id_fkey'), 'session_events', type_='foreignkey')
    op.create_foreign_key(None, 'session_events', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_curriculum_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sessions', 'curricula', ['curriculum_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('skill_model_user_id_fkey'), 'skill_model', type_='foreignkey')
    op.drop_constraint(op.f('skill_model_concept_id_fkey'), 'skill_model', type_='foreignkey')
    op.create_foreign_key(None, 'skill_model', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'skill_model', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tests_exercise_id_fkey'), 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(op.f('tests_exercise_id_fkey'), 'tests', 'exercises', ['exercise_id'], ['id'])
    op.drop_constraint(None, 'skill_model', type_='foreignkey')
    op.drop_constraint(None, 'skill_model', type_='foreignkey')
    op.create_foreign_key(op.f('skill_model_concept_id_fkey'), 'skill_model', 'concepts', ['concept_id'], ['id'])
    op.create_foreign_key(op.f('skill_model_user_id_fkey'), 'skill_model', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_curriculum_id_fkey'), 'sessions', 'curricula', ['curriculum_id'], ['id'])
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'session_events', type_='foreignkey')
    op.create_foreign_key(op.f('session_events_session_id_fkey'), 'session_events', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'segments', type_='foreignkey')
    op.create_foreign_key(op.f('segments_curriculum_id_fkey'), 'segments', 'curricula', ['curriculum_id'], ['id'])
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_foreign_key(op.f('exercises_checkpoint_id_fkey'), 'exercises', 'checkpoints', ['checkpoint_id'], ['id'])
    op.drop_constraint(None, 'eval_results', type_='foreignkey')
    op.drop_constraint(None, 'eval_results', type_='foreignkey')
    op.create_foreign_key(op.f('eval_results_session_event_id_fkey'), 'eval_results', 'session_events', ['session_event_id'], ['id'])
    op.create_foreign_key(op.f('eval_results_exercise_id_fkey'), 'eval_results', 'exercises', ['exercise_id'], ['id'])
    op.drop_constraint(None, 'curricula', type_='foreignkey')
    op.create_foreign_key(op.f('curricula_tenant_id_fkey'), 'curricula', 'tenants', ['tenant_id'], ['id'])
    op.create_index(op.f('ix_curricula_user'), 'curricula', ['user_id'], unique=False)
    op.drop_constraint(None, 'concepts', type_='foreignkey')
    op.create_foreign_key(op.f('concepts_curriculum_id_fkey'), 'concepts', 'curricula', ['curriculum_id'], ['id'])
    op.drop_constraint(None, 'concept_edges', type_='foreignkey')
    op.drop_constraint(None, 'concept_edges', type_='foreignkey')
    op.create_foreign_key(op.f('concept_edges_target_id_fkey'), 'concept_edges', 'concepts', ['target_id'], ['id'])
    op.create_foreign_key(op.f('concept_edges_source_id_fkey'), 'concept_edges', 'concepts', ['source_id'], ['id'])
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.create_foreign_key(op.f('checkpoints_concept_id_fkey'), 'checkpoints', 'concepts', ['concept_id'], ['id'])
    op.create_foreign_key(op.f('checkpoints_curriculum_id_fkey'), 'checkpoints', 'curricula', ['curriculum_id'], ['id'])
    op.create_foreign_key(op.f('checkpoints_segment_id_fkey'), 'checkpoints', 'segments', ['segment_id'], ['id'])
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.drop_constraint(None, 'artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('artifacts_curriculum_id_fkey'), 'artifacts', 'curricula', ['curriculum_id'], ['id'])
    op.create_foreign_key(op.f('artifacts_tenant_id_fkey'), 'artifacts', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_user_interest_centroids_user_id'), table_name='user_interest_centroids')
    op.drop_table('user_interest_centroids')
    op.drop_table('user_skill_profiles')
    op.drop_index(op.f('ix_resource_nodes_tags'), table_name='resource_nodes')
    op.drop_table('resource_nodes')
    # ### end Alembic commands ###
